### ISSUE TITLE
Crash on Startup [1.20.1] [Java:17.0.9] [Forge:47.3.12]

### ISSUE THREAD

**Issue by Kyorith** [Forixaim/Trick-Weapons#15]
Tested in Isolation with only Epic Fight and this Mod installed.

[crash-2024-12-19_17.15.45-fml.txt](https://github.com/user-attachments/files/18200542/crash-2024-12-19_17.15.45-fml.txt)

**Comment by Forixaim** [comment]
What you're playing is the ancient caveman version of Battle Arts.

It's likely you have got that from Modrinth but yeah latest versions always release on CurseForge.

**Comment by Kyorith** [comment]
Yeah i did get it on Modrinth. Would it be possible to add a warning to the Modrinth page that it's an incompatible older version? I'm sure i won't be the only one with this issue.

**Comment by Forixaim** [comment]
> Yeah i did get it on Modrinth. Would it be possible to add a warning to the Modrinth page that it's an incompatible older version? I'm sure i won't be the only one with this issue.

I'm now updating the mod on both CurseForge and Modrinth now. Thanks for your patience.
